version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./api/:/var/www/html/api/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - db
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
